## An Ansible playbook to deploy OSRM project on
## single Ubuntu 16.04 machine. This playbook written by
## Roozbeh Shafiee (me@roozbeh.cloud)

## github: https://github.com/roozbehshafiee/ansiblify_osrm
